# All modules to be tested, with their module-specific transformations
modules:
  # - name: lineinfile
  #   path: modules/ansible/test/integration/targets/lineinfile
  #   type: ansible
  #   transformations:

  # - name: read_csv
  #   path: modules/community/tests/integration/targets/read_csv
  #   type: ansible
  #   transformations:

  - name: archive
    path: modules/puppet-archive
    type: puppet
    transformations:
      - name: prepend_dotslash
        options:
          keys: [archive]

# Transformations to do for every module
general_transformations: